config/routes.rb
Rails.application.routes.draw do
  get 'post/index'
  root 'post#index'

  resources :contatos
  resources :reservas
  resources :estruturas
  resources :paginas

end

app/models/contato.rb
class Contato < ActiveRecord::Base
end

app/models/estrutura.rb
class Estrutura < ActiveRecord::Base
end

app/models/pagina.rb
class Pagina < ActiveRecord::Base
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  # GET /contatos
  # GET /contatos.json
  def index
    @contatos = Contato.all
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: 'Contato was successfully created.' }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: 'Contato was successfully updated.' }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: 'Contato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contato_params
      params.require(:contato).permit(:body)
    end
end

app/controllers/estruturas_controller.rb
class EstruturasController < ApplicationController
  before_action :set_estrutura, only: [:show, :edit, :update, :destroy]

  # GET /estruturas
  # GET /estruturas.json
  def index
    @estruturas = Estrutura.all
  end

  # GET /estruturas/1
  # GET /estruturas/1.json
  def show
  end

  # GET /estruturas/new
  def new
    @estrutura = Estrutura.new
  end

  # GET /estruturas/1/edit
  def edit
  end

  # POST /estruturas
  # POST /estruturas.json
  def create
    @estrutura = Estrutura.new(estrutura_params)

    respond_to do |format|
      if @estrutura.save
        format.html { redirect_to @estrutura, notice: 'Estrutura was successfully created.' }
        format.json { render :show, status: :created, location: @estrutura }
      else
        format.html { render :new }
        format.json { render json: @estrutura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estruturas/1
  # PATCH/PUT /estruturas/1.json
  def update
    respond_to do |format|
      if @estrutura.update(estrutura_params)
        format.html { redirect_to @estrutura, notice: 'Estrutura was successfully updated.' }
        format.json { render :show, status: :ok, location: @estrutura }
      else
        format.html { render :edit }
        format.json { render json: @estrutura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estruturas/1
  # DELETE /estruturas/1.json
  def destroy
    @estrutura.destroy
    respond_to do |format|
      format.html { redirect_to estruturas_url, notice: 'Estrutura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estrutura
      @estrutura = Estrutura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estrutura_params
      params.require(:estrutura).permit(:body)
    end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  before_action :set_pagina, only: [:show, :edit, :update, :destroy]

  # GET /paginas
  # GET /paginas.json
  def index
    @paginas = Pagina.all
  end

  # GET /paginas/1
  # GET /paginas/1.json
  def show
  end

  # GET /paginas/new
  def new
    @pagina = Pagina.new
  end

  # GET /paginas/1/edit
  def edit
  end

  # POST /paginas
  # POST /paginas.json
  def create
    @pagina = Pagina.new(pagina_params)

    respond_to do |format|
      if @pagina.save
        format.html { redirect_to @pagina, notice: 'Pagina was successfully created.' }
        format.json { render :show, status: :created, location: @pagina }
      else
        format.html { render :new }
        format.json { render json: @pagina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paginas/1
  # PATCH/PUT /paginas/1.json
  def update
    respond_to do |format|
      if @pagina.update(pagina_params)
        format.html { redirect_to @pagina, notice: 'Pagina was successfully updated.' }
        format.json { render :show, status: :ok, location: @pagina }
      else
        format.html { render :edit }
        format.json { render json: @pagina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paginas/1
  # DELETE /paginas/1.json
  def destroy
    @pagina.destroy
    respond_to do |format|
      format.html { redirect_to paginas_url, notice: 'Pagina was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pagina
      @pagina = Pagina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pagina_params
      params.require(:pagina).permit(:body)
    end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
  end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]

  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.all
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
  end

  # GET /reservas/new
  def new
    @reserva = Reserva.new
  end

  # GET /reservas/1/edit
  def edit
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(reserva_params)

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: 'Reserva was successfully created.' }
        format.json { render :show, status: :created, location: @reserva }
      else
        format.html { render :new }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservas/1
  # PATCH/PUT /reservas/1.json
  def update
    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserva }
      else
        format.html { render :edit }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva.destroy
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: 'Reserva was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserva_params
      params.require(:reserva).permit(:nome, :telefone, :email, :dia, :horario)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/estruturas_helper.rb
module EstruturasHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/contatos/_form.html.erb
<%= simple_form_for @contato, :html => { :class => 'form-vertical' } do |f| %>
  <div class="form-inputs" >
      <%= f.input :body %>
  </div>
  
  
  <div class="form.actions">
      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  contatos_path, :class => 'btn btn-default' %>

  </div>

  
<% end %>

app/views/contatos/edit.html.erb
<%- model_class = Contato -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/contatos/index.html.erb
<%- model_class = Contato -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @contatos.each do |contato| %>
      <tr>
        <td><%= link_to contato.id, contato_path(contato) %></td>
        <td><%= contato.body %></td>
        <td><%=l contato.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_contato_path(contato), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      contato_path(contato),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_contato_path,
            :class => 'btn btn-primary' %>

app/views/contatos/new.html.erb
<%- model_class = Contato -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/contatos/show.html.erb
<%- model_class = Contato -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @contato.body %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              contatos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_contato_path(@contato), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              contato_path(@contato),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/estruturas/_form.html.erb
<%= simple_form_for @estrutura, :html => { :class => 'form-vertical' } do |f| %>
  <div class="form.inputs">
			<%= f.input :body %>
  </div>
  

  <div class="form.actions">
	  		 <%= f.button :submit, :class => 'btn-primary' %>
	 		 <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	                estruturas_path, :class => 'btn btn-default' %>

  </div>
 
<% end %>

app/views/estruturas/edit.html.erb
<%- model_class = Estrutura -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/estruturas/index.html.erb
<%- model_class = Estrutura -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @estruturas.each do |estrutura| %>
      <tr>
        <td><%= link_to estrutura.id, estrutura_path(estrutura) %></td>
        <td><%= estrutura.body %></td>
        <td><%=l estrutura.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_estrutura_path(estrutura), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      estrutura_path(estrutura),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_estrutura_path,
            :class => 'btn btn-primary' %>

app/views/estruturas/new.html.erb
<%- model_class = Estrutura -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/estruturas/show.html.erb
<%- model_class = Estrutura -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @estrutura.body %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              estruturas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_estrutura_path(@estrutura), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              estrutura_path(@estrutura),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/_navbar_site.html.erb
<%= nav_bar fixed: :top, brand: "Ruby Store", responsive: true do %>
  <%= menu_group do %>
      <%= menu_item "Home", paginas_path %>
      <%= menu_item "Estrutura", estruturas_path %>
      <%= menu_item "Reservas", reservas_path %>
      <%= menu_item "Contatos", contatos_path %>
     
  <% end -%>

  <%= menu_group :pull => :right do %>
    
      <%= menu_item current_user.email, paginas_path -%>
      <%= menu_item 'Sair', destroy_user_session_path, :method => Devise.sign_out_via -%>
   
    <%= menu_item 'Entrar', new_user_session_path -%>
    
        
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ArenaFutebol" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-fluid-top">
      <div class="container-fluid">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">ArenaFutebol</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= menu_item "Home", paginas_path  %></li>
            <li><%= menu_item "Estrutura", estruturas_path  %></li>
            <li><%= menu_item "Reserva", reservas_path  %></li>
            <li><%= menu_item "Contatos", contatos_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/paginas/_form.html.erb
<%= simple_form_for @pagina, :html => { :class => 'form-horizontal' } do |f| %>
 
  <div class="form_inputs">
  		<%= f.input :body %>
  </div>
 
  <div class="form_actions">
  	
		<%= f.button :submit, :class => 'btn-primary' %>
	  	<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
		                paginas_path, :class => 'btn btn-default' %>

  </div>

		  
<% end %>

app/views/paginas/edit.html.erb
<%- model_class = Pagina -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/paginas/index.html.erb
<%- model_class = Pagina -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @paginas.each do |pagina| %>
      <tr>
        <td><%= link_to pagina.id, pagina_path(pagina) %></td>
        <td><%= pagina.body %></td>
        <td><%=l pagina.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_pagina_path(pagina), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      pagina_path(pagina),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_pagina_path,
            :class => 'btn btn-primary' %>

app/views/paginas/new.html.erb
<%- model_class = Pagina -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/paginas/show.html.erb
<%- model_class = Pagina -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @pagina.body %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              paginas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_pagina_path(@pagina), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              pagina_path(@pagina),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/post/index.html.erb
<h1>::. Arena Futebol .:: </h1>
<p>Seja bem vindo!! </p>

app/views/reservas/_form.html.erb
<%= simple_form_for @reserva, :html => { :class => 'form-vertical' } do |f| %>
  <div class="form_inputs">
    
      <%= f.input :nome %>
      <%= f.input :telefone %>
      <%= f.input :email %>
      <%= f.input :dia %>
      <%= f.input :horario %>

  </div>

  
     
  <div>
      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                reservas_path, :class => 'btn btn-default' %>


  </div>
<% end %>

app/views/reservas/edit.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reservas/index.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:telefone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:dia) %></th>
      <th><%= model_class.human_attribute_name(:horario) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= link_to reserva.id, reserva_path(reserva) %></td>
        <td><%= reserva.nome %></td>
        <td><%= reserva.telefone %></td>
        <td><%= reserva.email %></td>
        <td><%= reserva.dia %></td>
        <td><%= reserva.horario %></td>
        <td><%=l reserva.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_reserva_path(reserva), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      reserva_path(reserva),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_reserva_path,
            :class => 'btn btn-primary' %>

app/views/reservas/new.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reservas/show.html.erb
<%- model_class = Reserva -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @reserva.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefone) %>:</strong></dt>
  <dd><%= @reserva.telefone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @reserva.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dia) %>:</strong></dt>
  <dd><%= @reserva.dia %></dd>
  <dt><strong><%= model_class.human_attribute_name(:horario) %>:</strong></dt>
  <dd><%= @reserva.horario %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              reservas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_reserva_path(@reserva), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              reserva_path(@reserva),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>